game.Print("===== Entity Tests Start =====")
ent = entity.Spawn()
ent:SetClassName("foobar")
game.Print("...spawned ", ent:GetClassName(), " ", ent:GetNumber())
game.Print(ent)
game.Print("===== Entity Tests End =====")
